/**
 * Inserts og:image + twitter:card meta into every article page, the article
 * hubs and /links/ on both sites (2026-08-31, one-time; idempotent).
 * Image URLs point at /img/og/<slug>.jpg generated by generate_og_images.js.
 * Run: node inject_og_meta.js [--dry]
 */

const fs = require('fs');
const path = require('path');

const DRY = process.argv.includes('--dry');
const FIN = __dirname;
const ENG = 'C:\\Users\\toyou\\OneDrive\\04. Work (TOYO) from 2025 Aug\\Work TOYO\\03. WFE\\03. Course Materials\\04. English Learning for Japanese\\Udemy Course\\deploy';

const SITES = [
  { root: FIN, host: 'https://worldfinanceedu.com', extra: [['articles', 'articles-hub'], ['links', 'links']] },
  { root: ENG, host: 'https://english.worldfinanceedu.com', extra: [['articles', 'articles-hub']] },
];

let changed = 0, skipped = 0, missingImg = 0;

for (const site of SITES) {
  const jobs = [];
  const artDir = path.join(site.root, 'articles');
  for (const d of fs.readdirSync(artDir, { withFileTypes: true })) {
    if (!d.isDirectory()) continue;
    jobs.push({ file: path.join(artDir, d.name, 'index.html'), slug: d.name });
  }
  for (const [p, slug] of site.extra) {
    jobs.push({ file: path.join(site.root, p, 'index.html'), slug });
  }

  for (const job of jobs) {
    if (!fs.existsSync(job.file)) continue;
    let html = fs.readFileSync(job.file, 'utf8');
    if (html.includes('og:image')) { skipped++; continue; }
    const imgFile = path.join(site.root, 'img', 'og', job.slug + '.jpg');
    if (!fs.existsSync(imgFile)) { console.warn('NO IMAGE for ' + job.slug); missingImg++; continue; }
    const imgUrl = site.host + '/img/og/' + job.slug + '.jpg';
    const block =
      '<meta property="og:image" content="' + imgUrl + '">\n' +
      '<meta property="og:image:width" content="1200">\n' +
      '<meta property="og:image:height" content="630">\n' +
      '<meta name="twitter:card" content="summary_large_image">\n' +
      '<meta name="twitter:image" content="' + imgUrl + '">\n';

    const ogUrlRe = /(<meta property="og:url"[^>]*>\s*\n)/;
    const titleRe = /(<\/title>\s*\n)/;
    let out;
    if (ogUrlRe.test(html)) out = html.replace(ogUrlRe, '$1' + block);
    else if (titleRe.test(html)) out = html.replace(titleRe, '$1' + block);
    else { console.warn('NO ANCHOR in ' + job.file); continue; }

    if (!DRY) fs.writeFileSync(job.file, out);
    console.log((DRY ? '[dry] ' : '') + 'og:image -> ' + (site.host.includes('english') ? 'eng' : 'fin') + '/' + job.slug);
    changed++;
  }
}
console.log('Done: ' + changed + ' injected, ' + skipped + ' already had og:image, ' + missingImg + ' missing image');
